"""Walkthroughs: a synthetic frame and two bundled scikit-learn datasets.

Usage (from the repository root)::

    python -m research.feature_audit.demo --dataset {synthetic,wine,breast_cancer} \
        --output-dir PATH [--permutations B] [--subsamples S] [--overwrite]

Writes exactly two files, ``demo-<dataset>.json`` and ``demo-<dataset>.md``,
into the requested directory, and refuses to overwrite them without
``--overwrite``. Outputs hold aggregates only, never rows or category labels.
Bundled datasets load from the installed scikit-learn package. There is no
network access.
"""

from __future__ import annotations

import argparse
import json
import time
from itertools import combinations
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from research.feature_audit.prototype import audit
from research.feature_audit.prototype.association import mi_bits, seed_for
from research.feature_audit.prototype.report import escape_markdown
from research.feature_audit.run_validation import source_hash

DATASETS = ("synthetic", "wine", "breast_cancer")
SPLIT_SEED = 42
TRAIN_FRACTION = 0.7

SOURCE_NOTES = {
    "synthetic": (
        "Generated by research/feature_audit/demo.py (fixed seed 2026). Every "
        "mechanism is planted on purpose; nothing here describes real customers."
    ),
    "wine": (
        "UCI ML Wine recognition data, as bundled with scikit-learn (load_wine). "
        "The installed description names R.A. Fisher as creator and Forina, M. et al. "
        "(PARVUS, Institute of Pharmaceutical and Food Analysis and Technologies, "
        "Genoa) as original owners, and cites Lichman, M. (2013), UCI Machine Learning "
        "Repository. The installed description states no license terms."
    ),
    "breast_cancer": (
        "UCI ML Breast Cancer Wisconsin (Diagnostic) data, as bundled with scikit-learn "
        "(load_breast_cancer). The installed description names Wolberg, Street and "
        "Mangasarian as creators and Nick Street as donor (November 1995). The installed "
        "description states no license terms."
    ),
}
_DESCR_CHECKS = {"wine": ("Forina", "Lichman"), "breast_cancer": ("Wolberg", "Nick Street")}

TYPE_NOTES = {
    "synthetic": "declared explicitly per column; support_calls is deliberately declared "
    "continuous to show the ambiguous_discrete review flag.",
    "wine": "all predictors declared continuous; exclusions are reported as they fall.",
    "breast_cancer": "all predictors declared continuous; exclusions are reported as they fall.",
}

DISCLAIMERS = {
    "synthetic": "Synthetic demonstration data.",
    "wine": "A statistical walkthrough of a public teaching dataset. Associations are "
    "descriptive only: no causal or predictive claim is made.",
    "breast_cancer": "A statistical walkthrough of a public teaching dataset. This is "
    "NOT medical guidance, and associations here say nothing clinical, causal or "
    "predictive.",
}


def synthetic_frame(seed: int = 2026) -> Tuple[pd.DataFrame, Dict[str, str]]:
    """A churn-like training frame with planted, known mechanisms."""
    rng = np.random.default_rng(seed)
    n = 600
    churned = rng.permutation(np.tile([0, 1], n // 2))
    tenure = np.where(churned == 1, rng.normal(0, 1, n), rng.normal(0, 3, n))
    plan = np.where(
        rng.random(n) < 0.35 + 0.3 * churned,
        "plan-bronze",
        rng.choice(["plan-silver", "plan-gold"], n),
    )
    region = rng.choice(["region-north", "region-south", "region-east"], n)
    region[rng.choice(n, 3, replace=False)] = "region-island"  # rare category
    last_login = pd.Series(rng.exponential(10, n))
    last_login[rng.random(n) < np.where(churned == 1, 0.35, 0.08)] = np.nan
    df = pd.DataFrame(
        {
            "tenure": tenure,
            "tenure_copy": tenure.copy(),
            "monthly_spend": rng.gamma(2.0, 20.0, n),
            "plan": plan,
            "region": region,
            "customer_id": [f"cust-{k:05d}" for k in rng.permutation(n)],
            "row_number": np.arange(n, dtype=float),
            "promo_flag": ["promo-none"] * n,
            "last_login_days": last_login,
            "support_calls": rng.integers(0, 5, n).astype(float),
            "churned": churned,
        }
    )
    types = {
        "tenure": "continuous",
        "tenure_copy": "continuous",
        "monthly_spend": "continuous",
        "plan": "categorical",
        "region": "categorical",
        "customer_id": "categorical",
        "row_number": "continuous",
        "promo_flag": "categorical",
        "last_login_days": "continuous",
        "support_calls": "continuous",
    }
    return df, types


def load_dataset(name: str):
    """Return (training frame, target name, feature types, split info)."""
    if name == "synthetic":
        df, types = synthetic_frame()
        split = {
            "stratified": False,
            "note": "synthetic frame used whole as training data",
            "train_rows": len(df),
            "holdout_rows": 0,
            "holdout_used": False,
        }
        return df, "churned", types, split
    from sklearn import datasets
    from sklearn.model_selection import train_test_split

    loader = {"wine": datasets.load_wine, "breast_cancer": datasets.load_breast_cancer}[name]
    bunch = loader(as_frame=True)
    for token in _DESCR_CHECKS[name]:
        if token not in bunch.DESCR:
            raise RuntimeError(f"installed {name} description changed; re-check source notes")
    frame = bunch.frame.copy()
    target = "target"
    train, holdout = train_test_split(
        frame, train_size=TRAIN_FRACTION, stratify=frame[target], random_state=SPLIT_SEED
    )
    del holdout  # never audited or inspected
    split = {
        "stratified": True,
        "train_fraction": TRAIN_FRACTION,
        "random_state": SPLIT_SEED,
        "train_rows": len(train),
        "holdout_rows": len(frame) - len(train),
        "holdout_used": False,
    }
    types = {c: "continuous" for c in train.columns if c != target}
    return train, target, types, split


def _codes(series: pd.Series) -> np.ndarray:
    codes, _ = pd.factorize(series, sort=False, use_na_sentinel=True)
    return codes


def baseline(df: pd.DataFrame, target: str, types: Dict[str, str], seed: int) -> dict:
    """What pandas and raw sklearn MI give without the audit's context."""
    y, _ = pd.factorize(df[target], sort=False)
    binary = len(np.unique(y)) == 2
    rows = []
    for name, kind in types.items():
        s = df[name]
        observed = s.notna().to_numpy()
        r = None
        if binary and kind == "continuous" and observed.sum() > 2:
            x = s.to_numpy(dtype=float)[observed]
            if np.std(x) > 0:
                r = float(np.corrcoef(x, y[observed])[0, 1])
        raw = None
        if observed.sum() >= 10 and len(np.unique(y[observed])) >= 2:
            x = _codes(s)[observed] if kind == "categorical" else s.to_numpy(dtype=float)[observed]
            raw = mi_bits(x, y[observed], kind=kind, seed=seed_for(seed, name, "estimator:value"))
        rows.append(
            {
                "feature": name,
                "missing_count": int((~observed).sum()),
                "nunique": int(s.nunique(dropna=True)),
                "pearson_r_with_target": r,
                "raw_mi_bits": raw,
            }
        )
    dups = [[a, b] for a, b in combinations(types, 2) if df[a].equals(df[b])]
    return {"features": rows, "exact_duplicates": dups, "pearson_applicable": binary}


def _fmt(v):
    if v is None:
        return "—"
    if isinstance(v, float):
        return f"{v:.4g}"
    return str(v)


def render_markdown(name: str, payload: dict, report_md: str) -> str:
    run = payload["run"]
    lines = [
        f"# Feature-audit walkthrough: {name}",
        "",
        f"_{DISCLAIMERS[name]}_",
        "",
        "## Data",
        "",
        f"- Source: {SOURCE_NOTES[name]}",
        f"- Split: {json.dumps(payload['dataset']['split'])}",
        f"- Types: {TYPE_NOTES[name]}",
        "",
        "## Run",
        "",
        f"- Baseline (pandas + raw sklearn MI): {run['baseline_seconds']:.2f} s; "
        f"audit: {run['audit_seconds']:.1f} s.",
    ]
    if run["reduced_resampling"]:
        lines.append(
            f"- **Reduced resampling** (B={run['n_permutations']}, "
            f"{run['n_subsamples']} subsamples): a smoke run, not an official walkthrough."
        )
    lines += [
        "",
        "## Baseline",
        "",
        "Pandas already shows missing counts, distinct counts and exact duplicates; the "
        "audit repeats those deliberately. Raw MI is scikit-learn's estimate with the same "
        "masks, types and estimator seed as the audit, but without null context.",
        "",
        "| feature | missing | distinct | Pearson r (binary target) | raw MI (bits) |",
        "|---|---|---|---|---|",
    ]
    for b in payload["baseline"]["features"]:
        lines.append(
            f"| {escape_markdown(b['feature'])} | {b['missing_count']} | {b['nunique']} | "
            f"{_fmt(b['pearson_r_with_target'])} | {_fmt(b['raw_mi_bits'])} |"
        )
    dups = payload["baseline"]["exact_duplicates"]
    lines += [
        "",
        "Pandas exact duplicates (untyped): "
        + (", ".join(f"{escape_markdown(a)} = {escape_markdown(b)}" for a, b in dups) or "none"),
    ]
    lines += ["", "## What the audit adds here", ""] + [
        f"- {t}" for t in compare(payload["baseline"], payload["audit"], escape_markdown)
    ]
    lines += ["", "## Audit report", ""]
    lines += [("##" + line) if line.startswith("#") else line for line in report_md.splitlines()]
    return "\n".join(lines) + "\n"


def compare(base: dict, report: dict, escape=lambda name: name) -> List[str]:
    """Deterministic statements contrasting raw MI with the audit's context."""
    status = {f["feature"]: f["value_status"] for f in report["features"]}
    value_tests = {t["feature"]: t for t in report["tests"] if t["kind"] == "value"}
    excluded_with_mi = [
        b["feature"]
        for b in base["features"]
        if (b["raw_mi_bits"] or 0) > 0 and status[b["feature"]] != "eligible"
    ]
    not_distinguished = [
        f
        for f, t in value_tests.items()
        if t["assessment"] == "not_distinguished_from_null"
        and (next(b for b in base["features"] if b["feature"] == f)["raw_mi_bits"] or 0) > 0
    ]
    above = [f for f, t in value_tests.items() if t["assessment"] == "above_permutation_null"]
    missing = [
        t["feature"]
        for t in report["tests"]
        if t["kind"] == "missingness" and t["assessment"] == "above_permutation_null"
    ]
    esc = lambda names: ", ".join(escape(n) for n in names) or "none"  # noqa: E731
    return [
        f"Raw MI is positive but the audit withholds value inference ({len(excluded_with_mi)}): "
        f"{esc(excluded_with_mi)}. The exclusion codes say why. For identifiers and sparse "
        "categories, positive MI can reflect memorization; other codes flag a declared-type "
        "or support problem.",
        f"Positive raw MI, not distinguished from the shuffled-label null after Holm "
        f"({len(not_distinguished)}): {esc(not_distinguished)}.",
        f"Value associations above the permutation null ({len(above)}): {esc(above)}. "
        "This is association in this training sample, not causation or model value.",
        f"Missingness associated with the target ({len(missing)}): {esc(missing)}.",
        f"Holm family size m={report['metadata']['n_tests']}. Features are tested one at a "
        "time, so interactions are not examined.",
    ]


def main(argv: Optional[List[str]] = None) -> None:
    parser = argparse.ArgumentParser(description="Feature-audit walkthroughs")
    parser.add_argument("--dataset", choices=DATASETS, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--permutations", type=int, default=1999)
    parser.add_argument("--subsamples", type=int, default=30)
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args(argv)

    json_path = args.output_dir / f"demo-{args.dataset}.json"
    md_path = args.output_dir / f"demo-{args.dataset}.md"
    existing = [p for p in (json_path, md_path) if p.exists()]
    if existing and not args.overwrite:
        raise SystemExit(f"{existing[0]} exists; pass --overwrite to replace it")

    df, target, types, split = load_dataset(args.dataset)
    start = time.perf_counter()
    base = baseline(df, target, types, seed=0)
    baseline_seconds = time.perf_counter() - start
    start = time.perf_counter()
    report = audit(
        df,
        target=target,
        feature_types=types,
        assume_iid=True,
        n_permutations=args.permutations,
        n_subsamples=args.subsamples,
        random_state=0,
    )
    audit_seconds = time.perf_counter() - start
    report_dict = report.to_dict()
    payload = {
        "dataset": {
            "name": args.dataset,
            "source_notes": SOURCE_NOTES[args.dataset],
            "disclaimer": DISCLAIMERS[args.dataset],
            "split": split,
        },
        "run": {
            "baseline_seconds": baseline_seconds,
            "audit_seconds": audit_seconds,
            "n_permutations": args.permutations,
            "n_subsamples": args.subsamples,
            "reduced_resampling": args.permutations < 1999 or args.subsamples < 30,
            "source_hash": source_hash(),
        },
        "baseline": base,
        "audit": report_dict,
    }
    payload["comparison"] = compare(base, report_dict)
    md = render_markdown(args.dataset, payload, report.to_markdown())

    args.output_dir.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(payload, indent=1, allow_nan=False) + "\n")
    md_path.write_text(md)
    print(f"wrote {json_path} and {md_path} (audit {audit_seconds:.1f}s)")


if __name__ == "__main__":
    main()
